In [1]:
import torch
import numpy as np
x = torch.tensor([1,1]).to('cuda')
x.cpu().numpy()

array([1, 1])

In [2]:
import torchvision
import torch
batch_size =50
fixed_cset1 = torchvision.datasets.CIFAR10(root='./data', train=True,
                                           download=True, transform=None)
fixed_cset2 = torchvision.datasets.CIFAR10(root='./data', train=False,
                                           download=True, transform=None)
fixed_testset = torch.utils.data.ConcatDataset([fixed_cset1, fixed_cset2])

fixed_testloader = torch.utils.data.DataLoader(fixed_testset, batch_size=batch_size,
                                               shuffle=False)

Files already downloaded and verified
Files already downloaded and verified


In [2]:
len(fixed_testloader.dataset.classes)

AttributeError: 'ConcatDataset' object has no attribute 'classes'

In [27]:
dir(fixed_testset)
fixed_testset.cumsum

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [31]:
range(len(fixed_cset1))

range(0, 50000)

In [33]:
x = [y for y in range(60000)]

In [35]:
x[:len(fixed_cset1)][-10:]

[49990, 49991, 49992, 49993, 49994, 49995, 49996, 49997, 49998, 49999]

In [13]:
image_features = torch.tensor([[1.0,7.0,1.0,7.0],[1.0,7.0,1.0,7.0]])
image_features = image_features / \
    image_features.norm(dim=-1, keepdim=True)

In [14]:
image_features

tensor([[0.1000, 0.7000, 0.1000, 0.7000],
        [0.1000, 0.7000, 0.1000, 0.7000]])

tensor([[1.],
        [1.]])

In [14]:
image_features = torch.tensor([[1.0,1.0,1.0,1.0],[1.0,5.0,5.0,7.0]])
text_features = torch.ones((10,4))
text_features[:1] =2 

In [15]:
x = image_features @ text_features.t()

In [16]:
image_features

tensor([[1., 1., 1., 1.],
        [1., 5., 5., 7.]])

In [27]:
torch.argmax(x,dim=-1)

tensor([0, 0])

In [19]:
x

tensor([[ 8.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
        [36., 18., 18., 18., 18., 18., 18., 18., 18., 18.]])

In [29]:
x = np.array([[1,2],[3,4]])
y = np.array([[1],[2]])

x.shape

(2, 2)

In [30]:
y.shape

(2, 1)

In [33]:
x.T @ y

array([[ 7],
       [10]])

In [34]:
x @ y

array([[ 5],
       [11]])

In [35]:
def add(x):
    print(x)
add(3)

3


In [37]:
dd = add
dd

<function __main__.add(x)>

In [38]:
dd(add)

<function add at 0x7f3628439a60>


In [40]:
torch.LongTensor(x)

tensor([[1, 2],
        [3, 4]])

In [4]:
if 1 == 1: print('hi')
else: print('hi')

SyntaxError: unexpected character after line continuation character (<ipython-input-4-ea970a0bb218>, line 1)

In [8]:
import torch
lr = 0.001
model = torch.nn.Sequential(
    torch.nn.Linear(3, 1),
    torch.nn.Flatten(0, 1)
)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=lr,
    weight_decay=5e-4,
    betas=(0.9, 0.999),
)

In [22]:
dir(optimizer.state_dict)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__func__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [23]:
dir(optimizer)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_hook_for_profile',
 '_zero_grad_profile_name',
 'add_param_group',
 'defaults',
 'load_state_dict',
 'param_groups',
 'state',
 'state_dict',
 'step',
 'zero_grad']

In [28]:
optimizer

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.001
    weight_decay: 0.0005
)

In [30]:
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1000, gamma=0.5)

In [38]:
scheduler.step()

In [42]:
import clip
print(clip.available_models())

['RN50', 'RN101', 'RN50x4', 'RN50x16', 'RN50x64', 'ViT-B/32', 'ViT-B/16', 'ViT-L/14', 'ViT-L/14@336px']


In [44]:
dataset_name = 'tt'
clip_backbone = 'dd'
x = '_'.join(['npy_folder/',dataset_name, clip_backbone,'test_cluster.npy'])
x

'npy_folder/_tt_dd_test_cluster.npy'

In [46]:
clip_backbone = 'ViT-B/32'

In [50]:
if '/' in clip_backbone:
    clip_backbone = clip_backbone.replace('/','_')

In [52]:
clip_backbone = 'tt'

In [53]:
clip_backbone = clip_backbone.replace('/','_')

In [54]:
clip_backbone

'tt'

In [39]:
n_ctx = 16
name = 'y'
prompt_prefix = " ".join(["X"]*n_ctx)
prompt_prefix = 'a ' + prompt_prefix
classnames = [str(i) for i in range(10)]
prompts = [prompt_prefix + " "+ name+"." for name in classnames]
prompts

['a X X X X X X X X X X X X X X X X 0.',
 'a X X X X X X X X X X X X X X X X 1.',
 'a X X X X X X X X X X X X X X X X 2.',
 'a X X X X X X X X X X X X X X X X 3.',
 'a X X X X X X X X X X X X X X X X 4.',
 'a X X X X X X X X X X X X X X X X 5.',
 'a X X X X X X X X X X X X X X X X 6.',
 'a X X X X X X X X X X X X X X X X 7.',
 'a X X X X X X X X X X X X X X X X 8.',
 'a X X X X X X X X X X X X X X X X 9.']

In [40]:
prompts = " ".join(prompts)

In [41]:
prompt_prefix = prompt_prefix + ' b'

In [42]:
prompt_prefix = prompt_prefix.split(' ')
prompt_prefix

['a',
 'X',
 'X',
 'X',
 'X',
 'X',
 'X',
 'X',
 'X',
 'X',
 'X',
 'X',
 'X',
 'X',
 'X',
 'X',
 'X',
 'b']

In [43]:
prompt_prefix[:1]

['a']

In [44]:
prompt_prefix[1+n_ctx:]

['b']